-- -------------------------------------------------------------
--
-- Module: filter_serial
-- Generated by MATLAB(R) 9.8 and Filter Design HDL Coder 3.1.7.
-- Generated on: 2024-05-24 13:33:44
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TargetDirectory: D:\julianyhugo
-- Name: filter_serial
-- SerialPartition: 128
-- TestBenchStimulus: impulse step ramp chirp noise

-- -------------------------------------------------------------
-- HDL Implementation    : Fully Serial
-- Folding Factor        : 128
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 128
-- Stable            : Yes
-- Linear Phase      : Yes (Type 2)
-- Arithmetic        : fixed
-- Numerator         : s25,28 -> [-6.250000e-02 6.250000e-02)
-- Input             : s12,0 -> [-2048 2048)
-- Filter Internals  : Specify Precision
--   Output          : s10,0 -> [-512 512)
--   Product         : s36,26 -> [-512 512)
--   Accumulator     : s39,26 -> [-4096 4096)
--   Round Mode      : convergent
--   Overflow Mode   : wrap
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter_serial IS
   PORT( clk                             :   IN    std_logic;
         clk_enable                      :   IN    std_logic;
         reset                           :   IN    std_logic;
         filter_in                       :   IN    std_logic_vector(11 DOWNTO 0); -- sfix12
         filter_out                      :   OUT   std_logic_vector(9 DOWNTO 0)  -- sfix10
         );

END filter_serial;


----------------------------------------------------------------
--Module Architecture: filter_serial
----------------------------------------------------------------
ARCHITECTURE rtl OF filter_serial IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(11 DOWNTO 0); -- sfix12
  -- Constants
  CONSTANT coeff1                         : signed(24 DOWNTO 0) := to_signed(-46292, 25); -- sfix25_En28
  CONSTANT coeff2                         : signed(24 DOWNTO 0) := to_signed(-32488, 25); -- sfix25_En28
  CONSTANT coeff3                         : signed(24 DOWNTO 0) := to_signed(-43252, 25); -- sfix25_En28
  CONSTANT coeff4                         : signed(24 DOWNTO 0) := to_signed(-55871, 25); -- sfix25_En28
  CONSTANT coeff5                         : signed(24 DOWNTO 0) := to_signed(-70394, 25); -- sfix25_En28
  CONSTANT coeff6                         : signed(24 DOWNTO 0) := to_signed(-86834, 25); -- sfix25_En28
  CONSTANT coeff7                         : signed(24 DOWNTO 0) := to_signed(-105134, 25); -- sfix25_En28
  CONSTANT coeff8                         : signed(24 DOWNTO 0) := to_signed(-125243, 25); -- sfix25_En28
  CONSTANT coeff9                         : signed(24 DOWNTO 0) := to_signed(-146997, 25); -- sfix25_En28
  CONSTANT coeff10                        : signed(24 DOWNTO 0) := to_signed(-170163, 25); -- sfix25_En28
  CONSTANT coeff11                        : signed(24 DOWNTO 0) := to_signed(-194428, 25); -- sfix25_En28
  CONSTANT coeff12                        : signed(24 DOWNTO 0) := to_signed(-219498, 25); -- sfix25_En28
  CONSTANT coeff13                        : signed(24 DOWNTO 0) := to_signed(-244801, 25); -- sfix25_En28
  CONSTANT coeff14                        : signed(24 DOWNTO 0) := to_signed(-269845, 25); -- sfix25_En28
  CONSTANT coeff15                        : signed(24 DOWNTO 0) := to_signed(-293984, 25); -- sfix25_En28
  CONSTANT coeff16                        : signed(24 DOWNTO 0) := to_signed(-316474, 25); -- sfix25_En28
  CONSTANT coeff17                        : signed(24 DOWNTO 0) := to_signed(-336544, 25); -- sfix25_En28
  CONSTANT coeff18                        : signed(24 DOWNTO 0) := to_signed(-353256, 25); -- sfix25_En28
  CONSTANT coeff19                        : signed(24 DOWNTO 0) := to_signed(-365668, 25); -- sfix25_En28
  CONSTANT coeff20                        : signed(24 DOWNTO 0) := to_signed(-372727, 25); -- sfix25_En28
  CONSTANT coeff21                        : signed(24 DOWNTO 0) := to_signed(-373340, 25); -- sfix25_En28
  CONSTANT coeff22                        : signed(24 DOWNTO 0) := to_signed(-366348, 25); -- sfix25_En28
  CONSTANT coeff23                        : signed(24 DOWNTO 0) := to_signed(-350602, 25); -- sfix25_En28
  CONSTANT coeff24                        : signed(24 DOWNTO 0) := to_signed(-324884, 25); -- sfix25_En28
  CONSTANT coeff25                        : signed(24 DOWNTO 0) := to_signed(-288006, 25); -- sfix25_En28
  CONSTANT coeff26                        : signed(24 DOWNTO 0) := to_signed(-238782, 25); -- sfix25_En28
  CONSTANT coeff27                        : signed(24 DOWNTO 0) := to_signed(-176056, 25); -- sfix25_En28
  CONSTANT coeff28                        : signed(24 DOWNTO 0) := to_signed(-98752, 25); -- sfix25_En28
  CONSTANT coeff29                        : signed(24 DOWNTO 0) := to_signed(-5839, 25); -- sfix25_En28
  CONSTANT coeff30                        : signed(24 DOWNTO 0) := to_signed(103595, 25); -- sfix25_En28
  CONSTANT coeff31                        : signed(24 DOWNTO 0) := to_signed(230350, 25); -- sfix25_En28
  CONSTANT coeff32                        : signed(24 DOWNTO 0) := to_signed(375096, 25); -- sfix25_En28
  CONSTANT coeff33                        : signed(24 DOWNTO 0) := to_signed(538345, 25); -- sfix25_En28
  CONSTANT coeff34                        : signed(24 DOWNTO 0) := to_signed(720430, 25); -- sfix25_En28
  CONSTANT coeff35                        : signed(24 DOWNTO 0) := to_signed(921500, 25); -- sfix25_En28
  CONSTANT coeff36                        : signed(24 DOWNTO 0) := to_signed(1141494, 25); -- sfix25_En28
  CONSTANT coeff37                        : signed(24 DOWNTO 0) := to_signed(1380133, 25); -- sfix25_En28
  CONSTANT coeff38                        : signed(24 DOWNTO 0) := to_signed(1636924, 25); -- sfix25_En28
  CONSTANT coeff39                        : signed(24 DOWNTO 0) := to_signed(1911121, 25); -- sfix25_En28
  CONSTANT coeff40                        : signed(24 DOWNTO 0) := to_signed(2201761, 25); -- sfix25_En28
  CONSTANT coeff41                        : signed(24 DOWNTO 0) := to_signed(2507638, 25); -- sfix25_En28
  CONSTANT coeff42                        : signed(24 DOWNTO 0) := to_signed(2827315, 25); -- sfix25_En28
  CONSTANT coeff43                        : signed(24 DOWNTO 0) := to_signed(3159132, 25); -- sfix25_En28
  CONSTANT coeff44                        : signed(24 DOWNTO 0) := to_signed(3501215, 25); -- sfix25_En28
  CONSTANT coeff45                        : signed(24 DOWNTO 0) := to_signed(3851487, 25); -- sfix25_En28
  CONSTANT coeff46                        : signed(24 DOWNTO 0) := to_signed(4207694, 25); -- sfix25_En28
  CONSTANT coeff47                        : signed(24 DOWNTO 0) := to_signed(4567413, 25); -- sfix25_En28
  CONSTANT coeff48                        : signed(24 DOWNTO 0) := to_signed(4928082, 25); -- sfix25_En28
  CONSTANT coeff49                        : signed(24 DOWNTO 0) := to_signed(5287039, 25); -- sfix25_En28
  CONSTANT coeff50                        : signed(24 DOWNTO 0) := to_signed(5641528, 25); -- sfix25_En28
  CONSTANT coeff51                        : signed(24 DOWNTO 0) := to_signed(5988750, 25); -- sfix25_En28
  CONSTANT coeff52                        : signed(24 DOWNTO 0) := to_signed(6325885, 25); -- sfix25_En28
  CONSTANT coeff53                        : signed(24 DOWNTO 0) := to_signed(6650126, 25); -- sfix25_En28
  CONSTANT coeff54                        : signed(24 DOWNTO 0) := to_signed(6958719, 25); -- sfix25_En28
  CONSTANT coeff55                        : signed(24 DOWNTO 0) := to_signed(7248988, 25); -- sfix25_En28
  CONSTANT coeff56                        : signed(24 DOWNTO 0) := to_signed(7518372, 25); -- sfix25_En28
  CONSTANT coeff57                        : signed(24 DOWNTO 0) := to_signed(7764465, 25); -- sfix25_En28
  CONSTANT coeff58                        : signed(24 DOWNTO 0) := to_signed(7985034, 25); -- sfix25_En28
  CONSTANT coeff59                        : signed(24 DOWNTO 0) := to_signed(8178058, 25); -- sfix25_En28
  CONSTANT coeff60                        : signed(24 DOWNTO 0) := to_signed(8341755, 25); -- sfix25_En28
  CONSTANT coeff61                        : signed(24 DOWNTO 0) := to_signed(8474597, 25); -- sfix25_En28
  CONSTANT coeff62                        : signed(24 DOWNTO 0) := to_signed(8575341, 25); -- sfix25_En28
  CONSTANT coeff63                        : signed(24 DOWNTO 0) := to_signed(8643038, 25); -- sfix25_En28
  CONSTANT coeff64                        : signed(24 DOWNTO 0) := to_signed(8677047, 25); -- sfix25_En28
  CONSTANT coeff65                        : signed(24 DOWNTO 0) := to_signed(8677047, 25); -- sfix25_En28
  CONSTANT coeff66                        : signed(24 DOWNTO 0) := to_signed(8643038, 25); -- sfix25_En28
  CONSTANT coeff67                        : signed(24 DOWNTO 0) := to_signed(8575341, 25); -- sfix25_En28
  CONSTANT coeff68                        : signed(24 DOWNTO 0) := to_signed(8474597, 25); -- sfix25_En28
  CONSTANT coeff69                        : signed(24 DOWNTO 0) := to_signed(8341755, 25); -- sfix25_En28
  CONSTANT coeff70                        : signed(24 DOWNTO 0) := to_signed(8178058, 25); -- sfix25_En28
  CONSTANT coeff71                        : signed(24 DOWNTO 0) := to_signed(7985034, 25); -- sfix25_En28
  CONSTANT coeff72                        : signed(24 DOWNTO 0) := to_signed(7764465, 25); -- sfix25_En28
  CONSTANT coeff73                        : signed(24 DOWNTO 0) := to_signed(7518372, 25); -- sfix25_En28
  CONSTANT coeff74                        : signed(24 DOWNTO 0) := to_signed(7248988, 25); -- sfix25_En28
  CONSTANT coeff75                        : signed(24 DOWNTO 0) := to_signed(6958719, 25); -- sfix25_En28
  CONSTANT coeff76                        : signed(24 DOWNTO 0) := to_signed(6650126, 25); -- sfix25_En28
  CONSTANT coeff77                        : signed(24 DOWNTO 0) := to_signed(6325885, 25); -- sfix25_En28
  CONSTANT coeff78                        : signed(24 DOWNTO 0) := to_signed(5988750, 25); -- sfix25_En28
  CONSTANT coeff79                        : signed(24 DOWNTO 0) := to_signed(5641528, 25); -- sfix25_En28
  CONSTANT coeff80                        : signed(24 DOWNTO 0) := to_signed(5287039, 25); -- sfix25_En28
  CONSTANT coeff81                        : signed(24 DOWNTO 0) := to_signed(4928082, 25); -- sfix25_En28
  CONSTANT coeff82                        : signed(24 DOWNTO 0) := to_signed(4567413, 25); -- sfix25_En28
  CONSTANT coeff83                        : signed(24 DOWNTO 0) := to_signed(4207694, 25); -- sfix25_En28
  CONSTANT coeff84                        : signed(24 DOWNTO 0) := to_signed(3851487, 25); -- sfix25_En28
  CONSTANT coeff85                        : signed(24 DOWNTO 0) := to_signed(3501215, 25); -- sfix25_En28
  CONSTANT coeff86                        : signed(24 DOWNTO 0) := to_signed(3159132, 25); -- sfix25_En28
  CONSTANT coeff87                        : signed(24 DOWNTO 0) := to_signed(2827315, 25); -- sfix25_En28
  CONSTANT coeff88                        : signed(24 DOWNTO 0) := to_signed(2507638, 25); -- sfix25_En28
  CONSTANT coeff89                        : signed(24 DOWNTO 0) := to_signed(2201761, 25); -- sfix25_En28
  CONSTANT coeff90                        : signed(24 DOWNTO 0) := to_signed(1911121, 25); -- sfix25_En28
  CONSTANT coeff91                        : signed(24 DOWNTO 0) := to_signed(1636924, 25); -- sfix25_En28
  CONSTANT coeff92                        : signed(24 DOWNTO 0) := to_signed(1380133, 25); -- sfix25_En28
  CONSTANT coeff93                        : signed(24 DOWNTO 0) := to_signed(1141494, 25); -- sfix25_En28
  CONSTANT coeff94                        : signed(24 DOWNTO 0) := to_signed(921500, 25); -- sfix25_En28
  CONSTANT coeff95                        : signed(24 DOWNTO 0) := to_signed(720430, 25); -- sfix25_En28
  CONSTANT coeff96                        : signed(24 DOWNTO 0) := to_signed(538345, 25); -- sfix25_En28
  CONSTANT coeff97                        : signed(24 DOWNTO 0) := to_signed(375096, 25); -- sfix25_En28
  CONSTANT coeff98                        : signed(24 DOWNTO 0) := to_signed(230350, 25); -- sfix25_En28
  CONSTANT coeff99                        : signed(24 DOWNTO 0) := to_signed(103595, 25); -- sfix25_En28
  CONSTANT coeff100                       : signed(24 DOWNTO 0) := to_signed(-5839, 25); -- sfix25_En28
  CONSTANT coeff101                       : signed(24 DOWNTO 0) := to_signed(-98752, 25); -- sfix25_En28
  CONSTANT coeff102                       : signed(24 DOWNTO 0) := to_signed(-176056, 25); -- sfix25_En28
  CONSTANT coeff103                       : signed(24 DOWNTO 0) := to_signed(-238782, 25); -- sfix25_En28
  CONSTANT coeff104                       : signed(24 DOWNTO 0) := to_signed(-288006, 25); -- sfix25_En28
  CONSTANT coeff105                       : signed(24 DOWNTO 0) := to_signed(-324884, 25); -- sfix25_En28
  CONSTANT coeff106                       : signed(24 DOWNTO 0) := to_signed(-350602, 25); -- sfix25_En28
  CONSTANT coeff107                       : signed(24 DOWNTO 0) := to_signed(-366348, 25); -- sfix25_En28
  CONSTANT coeff108                       : signed(24 DOWNTO 0) := to_signed(-373340, 25); -- sfix25_En28
  CONSTANT coeff109                       : signed(24 DOWNTO 0) := to_signed(-372727, 25); -- sfix25_En28
  CONSTANT coeff110                       : signed(24 DOWNTO 0) := to_signed(-365668, 25); -- sfix25_En28
  CONSTANT coeff111                       : signed(24 DOWNTO 0) := to_signed(-353256, 25); -- sfix25_En28
  CONSTANT coeff112                       : signed(24 DOWNTO 0) := to_signed(-336544, 25); -- sfix25_En28
  CONSTANT coeff113                       : signed(24 DOWNTO 0) := to_signed(-316474, 25); -- sfix25_En28
  CONSTANT coeff114                       : signed(24 DOWNTO 0) := to_signed(-293984, 25); -- sfix25_En28
  CONSTANT coeff115                       : signed(24 DOWNTO 0) := to_signed(-269845, 25); -- sfix25_En28
  CONSTANT coeff116                       : signed(24 DOWNTO 0) := to_signed(-244801, 25); -- sfix25_En28
  CONSTANT coeff117                       : signed(24 DOWNTO 0) := to_signed(-219498, 25); -- sfix25_En28
  CONSTANT coeff118                       : signed(24 DOWNTO 0) := to_signed(-194428, 25); -- sfix25_En28
  CONSTANT coeff119                       : signed(24 DOWNTO 0) := to_signed(-170163, 25); -- sfix25_En28
  CONSTANT coeff120                       : signed(24 DOWNTO 0) := to_signed(-146997, 25); -- sfix25_En28
  CONSTANT coeff121                       : signed(24 DOWNTO 0) := to_signed(-125243, 25); -- sfix25_En28
  CONSTANT coeff122                       : signed(24 DOWNTO 0) := to_signed(-105134, 25); -- sfix25_En28
  CONSTANT coeff123                       : signed(24 DOWNTO 0) := to_signed(-86834, 25); -- sfix25_En28
  CONSTANT coeff124                       : signed(24 DOWNTO 0) := to_signed(-70394, 25); -- sfix25_En28
  CONSTANT coeff125                       : signed(24 DOWNTO 0) := to_signed(-55871, 25); -- sfix25_En28
  CONSTANT coeff126                       : signed(24 DOWNTO 0) := to_signed(-43252, 25); -- sfix25_En28
  CONSTANT coeff127                       : signed(24 DOWNTO 0) := to_signed(-32488, 25); -- sfix25_En28
  CONSTANT coeff128                       : signed(24 DOWNTO 0) := to_signed(-46292, 25); -- sfix25_En28

  -- Signals
  SIGNAL cur_count                        : unsigned(6 DOWNTO 0); -- ufix7
  SIGNAL phase_127                        : std_logic; -- boolean
  SIGNAL phase_0                          : std_logic; -- boolean
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 127); -- sfix12
  SIGNAL inputmux_1                       : signed(11 DOWNTO 0); -- sfix12
  SIGNAL acc_final                        : signed(38 DOWNTO 0); -- sfix39_En26
  SIGNAL acc_out_1                        : signed(38 DOWNTO 0); -- sfix39_En26
  SIGNAL product_1                        : signed(35 DOWNTO 0); -- sfix36_En26
  SIGNAL product_1_mux                    : signed(24 DOWNTO 0); -- sfix25_En28
  SIGNAL mul_temp                         : signed(36 DOWNTO 0); -- sfix37_En28
  SIGNAL prod_typeconvert_1               : signed(38 DOWNTO 0); -- sfix39_En26
  SIGNAL acc_sum_1                        : signed(38 DOWNTO 0); -- sfix39_En26
  SIGNAL acc_in_1                         : signed(38 DOWNTO 0); -- sfix39_En26
  SIGNAL add_temp                         : signed(39 DOWNTO 0); -- sfix40_En26
  SIGNAL output_typeconvert               : signed(9 DOWNTO 0); -- sfix10
  SIGNAL output_register                  : signed(9 DOWNTO 0); -- sfix10


BEGIN

  -- Block Statements
  Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(127, 7);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF cur_count >= to_unsigned(127, 7) THEN
          cur_count <= to_unsigned(0, 7);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS Counter_process;

  phase_127 <= '1' WHEN cur_count = to_unsigned(127, 7) AND clk_enable = '1' ELSE '0';

  phase_0 <= '1' WHEN cur_count = to_unsigned(0, 7) AND clk_enable = '1' ELSE '0';

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 127) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_127 = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 127) <= delay_pipeline(0 TO 126);
      END IF;
    END IF;
  END PROCESS Delay_Pipeline_process;

  inputmux_1 <= delay_pipeline(0) WHEN ( cur_count = to_unsigned(0, 7) ) ELSE
                     delay_pipeline(1) WHEN ( cur_count = to_unsigned(1, 7) ) ELSE
                     delay_pipeline(2) WHEN ( cur_count = to_unsigned(2, 7) ) ELSE
                     delay_pipeline(3) WHEN ( cur_count = to_unsigned(3, 7) ) ELSE
                     delay_pipeline(4) WHEN ( cur_count = to_unsigned(4, 7) ) ELSE
                     delay_pipeline(5) WHEN ( cur_count = to_unsigned(5, 7) ) ELSE
                     delay_pipeline(6) WHEN ( cur_count = to_unsigned(6, 7) ) ELSE
                     delay_pipeline(7) WHEN ( cur_count = to_unsigned(7, 7) ) ELSE
                     delay_pipeline(8) WHEN ( cur_count = to_unsigned(8, 7) ) ELSE
                     delay_pipeline(9) WHEN ( cur_count = to_unsigned(9, 7) ) ELSE
                     delay_pipeline(10) WHEN ( cur_count = to_unsigned(10, 7) ) ELSE
                     delay_pipeline(11) WHEN ( cur_count = to_unsigned(11, 7) ) ELSE
                     delay_pipeline(12) WHEN ( cur_count = to_unsigned(12, 7) ) ELSE
                     delay_pipeline(13) WHEN ( cur_count = to_unsigned(13, 7) ) ELSE
                     delay_pipeline(14) WHEN ( cur_count = to_unsigned(14, 7) ) ELSE
                     delay_pipeline(15) WHEN ( cur_count = to_unsigned(15, 7) ) ELSE
                     delay_pipeline(16) WHEN ( cur_count = to_unsigned(16, 7) ) ELSE
                     delay_pipeline(17) WHEN ( cur_count = to_unsigned(17, 7) ) ELSE
                     delay_pipeline(18) WHEN ( cur_count = to_unsigned(18, 7) ) ELSE
                     delay_pipeline(19) WHEN ( cur_count = to_unsigned(19, 7) ) ELSE
                     delay_pipeline(20) WHEN ( cur_count = to_unsigned(20, 7) ) ELSE
                     delay_pipeline(21) WHEN ( cur_count = to_unsigned(21, 7) ) ELSE
                     delay_pipeline(22) WHEN ( cur_count = to_unsigned(22, 7) ) ELSE
                     delay_pipeline(23) WHEN ( cur_count = to_unsigned(23, 7) ) ELSE
                     delay_pipeline(24) WHEN ( cur_count = to_unsigned(24, 7) ) ELSE
                     delay_pipeline(25) WHEN ( cur_count = to_unsigned(25, 7) ) ELSE
                     delay_pipeline(26) WHEN ( cur_count = to_unsigned(26, 7) ) ELSE
                     delay_pipeline(27) WHEN ( cur_count = to_unsigned(27, 7) ) ELSE
                     delay_pipeline(28) WHEN ( cur_count = to_unsigned(28, 7) ) ELSE
                     delay_pipeline(29) WHEN ( cur_count = to_unsigned(29, 7) ) ELSE
                     delay_pipeline(30) WHEN ( cur_count = to_unsigned(30, 7) ) ELSE
                     delay_pipeline(31) WHEN ( cur_count = to_unsigned(31, 7) ) ELSE
                     delay_pipeline(32) WHEN ( cur_count = to_unsigned(32, 7) ) ELSE
                     delay_pipeline(33) WHEN ( cur_count = to_unsigned(33, 7) ) ELSE
                     delay_pipeline(34) WHEN ( cur_count = to_unsigned(34, 7) ) ELSE
                     delay_pipeline(35) WHEN ( cur_count = to_unsigned(35, 7) ) ELSE
                     delay_pipeline(36) WHEN ( cur_count = to_unsigned(36, 7) ) ELSE
                     delay_pipeline(37) WHEN ( cur_count = to_unsigned(37, 7) ) ELSE
                     delay_pipeline(38) WHEN ( cur_count = to_unsigned(38, 7) ) ELSE
                     delay_pipeline(39) WHEN ( cur_count = to_unsigned(39, 7) ) ELSE
                     delay_pipeline(40) WHEN ( cur_count = to_unsigned(40, 7) ) ELSE
                     delay_pipeline(41) WHEN ( cur_count = to_unsigned(41, 7) ) ELSE
                     delay_pipeline(42) WHEN ( cur_count = to_unsigned(42, 7) ) ELSE
                     delay_pipeline(43) WHEN ( cur_count = to_unsigned(43, 7) ) ELSE
                     delay_pipeline(44) WHEN ( cur_count = to_unsigned(44, 7) ) ELSE
                     delay_pipeline(45) WHEN ( cur_count = to_unsigned(45, 7) ) ELSE
                     delay_pipeline(46) WHEN ( cur_count = to_unsigned(46, 7) ) ELSE
                     delay_pipeline(47) WHEN ( cur_count = to_unsigned(47, 7) ) ELSE
                     delay_pipeline(48) WHEN ( cur_count = to_unsigned(48, 7) ) ELSE
                     delay_pipeline(49) WHEN ( cur_count = to_unsigned(49, 7) ) ELSE
                     delay_pipeline(50) WHEN ( cur_count = to_unsigned(50, 7) ) ELSE
                     delay_pipeline(51) WHEN ( cur_count = to_unsigned(51, 7) ) ELSE
                     delay_pipeline(52) WHEN ( cur_count = to_unsigned(52, 7) ) ELSE
                     delay_pipeline(53) WHEN ( cur_count = to_unsigned(53, 7) ) ELSE
                     delay_pipeline(54) WHEN ( cur_count = to_unsigned(54, 7) ) ELSE
                     delay_pipeline(55) WHEN ( cur_count = to_unsigned(55, 7) ) ELSE
                     delay_pipeline(56) WHEN ( cur_count = to_unsigned(56, 7) ) ELSE
                     delay_pipeline(57) WHEN ( cur_count = to_unsigned(57, 7) ) ELSE
                     delay_pipeline(58) WHEN ( cur_count = to_unsigned(58, 7) ) ELSE
                     delay_pipeline(59) WHEN ( cur_count = to_unsigned(59, 7) ) ELSE
                     delay_pipeline(60) WHEN ( cur_count = to_unsigned(60, 7) ) ELSE
                     delay_pipeline(61) WHEN ( cur_count = to_unsigned(61, 7) ) ELSE
                     delay_pipeline(62) WHEN ( cur_count = to_unsigned(62, 7) ) ELSE
                     delay_pipeline(63) WHEN ( cur_count = to_unsigned(63, 7) ) ELSE
                     delay_pipeline(64) WHEN ( cur_count = to_unsigned(64, 7) ) ELSE
                     delay_pipeline(65) WHEN ( cur_count = to_unsigned(65, 7) ) ELSE
                     delay_pipeline(66) WHEN ( cur_count = to_unsigned(66, 7) ) ELSE
                     delay_pipeline(67) WHEN ( cur_count = to_unsigned(67, 7) ) ELSE
                     delay_pipeline(68) WHEN ( cur_count = to_unsigned(68, 7) ) ELSE
                     delay_pipeline(69) WHEN ( cur_count = to_unsigned(69, 7) ) ELSE
                     delay_pipeline(70) WHEN ( cur_count = to_unsigned(70, 7) ) ELSE
                     delay_pipeline(71) WHEN ( cur_count = to_unsigned(71, 7) ) ELSE
                     delay_pipeline(72) WHEN ( cur_count = to_unsigned(72, 7) ) ELSE
                     delay_pipeline(73) WHEN ( cur_count = to_unsigned(73, 7) ) ELSE
                     delay_pipeline(74) WHEN ( cur_count = to_unsigned(74, 7) ) ELSE
                     delay_pipeline(75) WHEN ( cur_count = to_unsigned(75, 7) ) ELSE
                     delay_pipeline(76) WHEN ( cur_count = to_unsigned(76, 7) ) ELSE
                     delay_pipeline(77) WHEN ( cur_count = to_unsigned(77, 7) ) ELSE
                     delay_pipeline(78) WHEN ( cur_count = to_unsigned(78, 7) ) ELSE
                     delay_pipeline(79) WHEN ( cur_count = to_unsigned(79, 7) ) ELSE
                     delay_pipeline(80) WHEN ( cur_count = to_unsigned(80, 7) ) ELSE
                     delay_pipeline(81) WHEN ( cur_count = to_unsigned(81, 7) ) ELSE
                     delay_pipeline(82) WHEN ( cur_count = to_unsigned(82, 7) ) ELSE
                     delay_pipeline(83) WHEN ( cur_count = to_unsigned(83, 7) ) ELSE
                     delay_pipeline(84) WHEN ( cur_count = to_unsigned(84, 7) ) ELSE
                     delay_pipeline(85) WHEN ( cur_count = to_unsigned(85, 7) ) ELSE
                     delay_pipeline(86) WHEN ( cur_count = to_unsigned(86, 7) ) ELSE
                     delay_pipeline(87) WHEN ( cur_count = to_unsigned(87, 7) ) ELSE
                     delay_pipeline(88) WHEN ( cur_count = to_unsigned(88, 7) ) ELSE
                     delay_pipeline(89) WHEN ( cur_count = to_unsigned(89, 7) ) ELSE
                     delay_pipeline(90) WHEN ( cur_count = to_unsigned(90, 7) ) ELSE
                     delay_pipeline(91) WHEN ( cur_count = to_unsigned(91, 7) ) ELSE
                     delay_pipeline(92) WHEN ( cur_count = to_unsigned(92, 7) ) ELSE
                     delay_pipeline(93) WHEN ( cur_count = to_unsigned(93, 7) ) ELSE
                     delay_pipeline(94) WHEN ( cur_count = to_unsigned(94, 7) ) ELSE
                     delay_pipeline(95) WHEN ( cur_count = to_unsigned(95, 7) ) ELSE
                     delay_pipeline(96) WHEN ( cur_count = to_unsigned(96, 7) ) ELSE
                     delay_pipeline(97) WHEN ( cur_count = to_unsigned(97, 7) ) ELSE
                     delay_pipeline(98) WHEN ( cur_count = to_unsigned(98, 7) ) ELSE
                     delay_pipeline(99) WHEN ( cur_count = to_unsigned(99, 7) ) ELSE
                     delay_pipeline(100) WHEN ( cur_count = to_unsigned(100, 7) ) ELSE
                     delay_pipeline(101) WHEN ( cur_count = to_unsigned(101, 7) ) ELSE
                     delay_pipeline(102) WHEN ( cur_count = to_unsigned(102, 7) ) ELSE
                     delay_pipeline(103) WHEN ( cur_count = to_unsigned(103, 7) ) ELSE
                     delay_pipeline(104) WHEN ( cur_count = to_unsigned(104, 7) ) ELSE
                     delay_pipeline(105) WHEN ( cur_count = to_unsigned(105, 7) ) ELSE
                     delay_pipeline(106) WHEN ( cur_count = to_unsigned(106, 7) ) ELSE
                     delay_pipeline(107) WHEN ( cur_count = to_unsigned(107, 7) ) ELSE
                     delay_pipeline(108) WHEN ( cur_count = to_unsigned(108, 7) ) ELSE
                     delay_pipeline(109) WHEN ( cur_count = to_unsigned(109, 7) ) ELSE
                     delay_pipeline(110) WHEN ( cur_count = to_unsigned(110, 7) ) ELSE
                     delay_pipeline(111) WHEN ( cur_count = to_unsigned(111, 7) ) ELSE
                     delay_pipeline(112) WHEN ( cur_count = to_unsigned(112, 7) ) ELSE
                     delay_pipeline(113) WHEN ( cur_count = to_unsigned(113, 7) ) ELSE
                     delay_pipeline(114) WHEN ( cur_count = to_unsigned(114, 7) ) ELSE
                     delay_pipeline(115) WHEN ( cur_count = to_unsigned(115, 7) ) ELSE
                     delay_pipeline(116) WHEN ( cur_count = to_unsigned(116, 7) ) ELSE
                     delay_pipeline(117) WHEN ( cur_count = to_unsigned(117, 7) ) ELSE
                     delay_pipeline(118) WHEN ( cur_count = to_unsigned(118, 7) ) ELSE
                     delay_pipeline(119) WHEN ( cur_count = to_unsigned(119, 7) ) ELSE
                     delay_pipeline(120) WHEN ( cur_count = to_unsigned(120, 7) ) ELSE
                     delay_pipeline(121) WHEN ( cur_count = to_unsigned(121, 7) ) ELSE
                     delay_pipeline(122) WHEN ( cur_count = to_unsigned(122, 7) ) ELSE
                     delay_pipeline(123) WHEN ( cur_count = to_unsigned(123, 7) ) ELSE
                     delay_pipeline(124) WHEN ( cur_count = to_unsigned(124, 7) ) ELSE
                     delay_pipeline(125) WHEN ( cur_count = to_unsigned(125, 7) ) ELSE
                     delay_pipeline(126) WHEN ( cur_count = to_unsigned(126, 7) ) ELSE
                     delay_pipeline(127);

  --   ------------------ Serial partition # 1 ------------------

  product_1_mux <= coeff1 WHEN ( cur_count = to_unsigned(0, 7) ) ELSE
                        coeff2 WHEN ( cur_count = to_unsigned(1, 7) ) ELSE
                        coeff3 WHEN ( cur_count = to_unsigned(2, 7) ) ELSE
                        coeff4 WHEN ( cur_count = to_unsigned(3, 7) ) ELSE
                        coeff5 WHEN ( cur_count = to_unsigned(4, 7) ) ELSE
                        coeff6 WHEN ( cur_count = to_unsigned(5, 7) ) ELSE
                        coeff7 WHEN ( cur_count = to_unsigned(6, 7) ) ELSE
                        coeff8 WHEN ( cur_count = to_unsigned(7, 7) ) ELSE
                        coeff9 WHEN ( cur_count = to_unsigned(8, 7) ) ELSE
                        coeff10 WHEN ( cur_count = to_unsigned(9, 7) ) ELSE
                        coeff11 WHEN ( cur_count = to_unsigned(10, 7) ) ELSE
                        coeff12 WHEN ( cur_count = to_unsigned(11, 7) ) ELSE
                        coeff13 WHEN ( cur_count = to_unsigned(12, 7) ) ELSE
                        coeff14 WHEN ( cur_count = to_unsigned(13, 7) ) ELSE
                        coeff15 WHEN ( cur_count = to_unsigned(14, 7) ) ELSE
                        coeff16 WHEN ( cur_count = to_unsigned(15, 7) ) ELSE
                        coeff17 WHEN ( cur_count = to_unsigned(16, 7) ) ELSE
                        coeff18 WHEN ( cur_count = to_unsigned(17, 7) ) ELSE
                        coeff19 WHEN ( cur_count = to_unsigned(18, 7) ) ELSE
                        coeff20 WHEN ( cur_count = to_unsigned(19, 7) ) ELSE
                        coeff21 WHEN ( cur_count = to_unsigned(20, 7) ) ELSE
                        coeff22 WHEN ( cur_count = to_unsigned(21, 7) ) ELSE
                        coeff23 WHEN ( cur_count = to_unsigned(22, 7) ) ELSE
                        coeff24 WHEN ( cur_count = to_unsigned(23, 7) ) ELSE
                        coeff25 WHEN ( cur_count = to_unsigned(24, 7) ) ELSE
                        coeff26 WHEN ( cur_count = to_unsigned(25, 7) ) ELSE
                        coeff27 WHEN ( cur_count = to_unsigned(26, 7) ) ELSE
                        coeff28 WHEN ( cur_count = to_unsigned(27, 7) ) ELSE
                        coeff29 WHEN ( cur_count = to_unsigned(28, 7) ) ELSE
                        coeff30 WHEN ( cur_count = to_unsigned(29, 7) ) ELSE
                        coeff31 WHEN ( cur_count = to_unsigned(30, 7) ) ELSE
                        coeff32 WHEN ( cur_count = to_unsigned(31, 7) ) ELSE
                        coeff33 WHEN ( cur_count = to_unsigned(32, 7) ) ELSE
                        coeff34 WHEN ( cur_count = to_unsigned(33, 7) ) ELSE
                        coeff35 WHEN ( cur_count = to_unsigned(34, 7) ) ELSE
                        coeff36 WHEN ( cur_count = to_unsigned(35, 7) ) ELSE
                        coeff37 WHEN ( cur_count = to_unsigned(36, 7) ) ELSE
                        coeff38 WHEN ( cur_count = to_unsigned(37, 7) ) ELSE
                        coeff39 WHEN ( cur_count = to_unsigned(38, 7) ) ELSE
                        coeff40 WHEN ( cur_count = to_unsigned(39, 7) ) ELSE
                        coeff41 WHEN ( cur_count = to_unsigned(40, 7) ) ELSE
                        coeff42 WHEN ( cur_count = to_unsigned(41, 7) ) ELSE
                        coeff43 WHEN ( cur_count = to_unsigned(42, 7) ) ELSE
                        coeff44 WHEN ( cur_count = to_unsigned(43, 7) ) ELSE
                        coeff45 WHEN ( cur_count = to_unsigned(44, 7) ) ELSE
                        coeff46 WHEN ( cur_count = to_unsigned(45, 7) ) ELSE
                        coeff47 WHEN ( cur_count = to_unsigned(46, 7) ) ELSE
                        coeff48 WHEN ( cur_count = to_unsigned(47, 7) ) ELSE
                        coeff49 WHEN ( cur_count = to_unsigned(48, 7) ) ELSE
                        coeff50 WHEN ( cur_count = to_unsigned(49, 7) ) ELSE
                        coeff51 WHEN ( cur_count = to_unsigned(50, 7) ) ELSE
                        coeff52 WHEN ( cur_count = to_unsigned(51, 7) ) ELSE
                        coeff53 WHEN ( cur_count = to_unsigned(52, 7) ) ELSE
                        coeff54 WHEN ( cur_count = to_unsigned(53, 7) ) ELSE
                        coeff55 WHEN ( cur_count = to_unsigned(54, 7) ) ELSE
                        coeff56 WHEN ( cur_count = to_unsigned(55, 7) ) ELSE
                        coeff57 WHEN ( cur_count = to_unsigned(56, 7) ) ELSE
                        coeff58 WHEN ( cur_count = to_unsigned(57, 7) ) ELSE
                        coeff59 WHEN ( cur_count = to_unsigned(58, 7) ) ELSE
                        coeff60 WHEN ( cur_count = to_unsigned(59, 7) ) ELSE
                        coeff61 WHEN ( cur_count = to_unsigned(60, 7) ) ELSE
                        coeff62 WHEN ( cur_count = to_unsigned(61, 7) ) ELSE
                        coeff63 WHEN ( cur_count = to_unsigned(62, 7) ) ELSE
                        coeff64 WHEN ( cur_count = to_unsigned(63, 7) ) ELSE
                        coeff65 WHEN ( cur_count = to_unsigned(64, 7) ) ELSE
                        coeff66 WHEN ( cur_count = to_unsigned(65, 7) ) ELSE
                        coeff67 WHEN ( cur_count = to_unsigned(66, 7) ) ELSE
                        coeff68 WHEN ( cur_count = to_unsigned(67, 7) ) ELSE
                        coeff69 WHEN ( cur_count = to_unsigned(68, 7) ) ELSE
                        coeff70 WHEN ( cur_count = to_unsigned(69, 7) ) ELSE
                        coeff71 WHEN ( cur_count = to_unsigned(70, 7) ) ELSE
                        coeff72 WHEN ( cur_count = to_unsigned(71, 7) ) ELSE
                        coeff73 WHEN ( cur_count = to_unsigned(72, 7) ) ELSE
                        coeff74 WHEN ( cur_count = to_unsigned(73, 7) ) ELSE
                        coeff75 WHEN ( cur_count = to_unsigned(74, 7) ) ELSE
                        coeff76 WHEN ( cur_count = to_unsigned(75, 7) ) ELSE
                        coeff77 WHEN ( cur_count = to_unsigned(76, 7) ) ELSE
                        coeff78 WHEN ( cur_count = to_unsigned(77, 7) ) ELSE
                        coeff79 WHEN ( cur_count = to_unsigned(78, 7) ) ELSE
                        coeff80 WHEN ( cur_count = to_unsigned(79, 7) ) ELSE
                        coeff81 WHEN ( cur_count = to_unsigned(80, 7) ) ELSE
                        coeff82 WHEN ( cur_count = to_unsigned(81, 7) ) ELSE
                        coeff83 WHEN ( cur_count = to_unsigned(82, 7) ) ELSE
                        coeff84 WHEN ( cur_count = to_unsigned(83, 7) ) ELSE
                        coeff85 WHEN ( cur_count = to_unsigned(84, 7) ) ELSE
                        coeff86 WHEN ( cur_count = to_unsigned(85, 7) ) ELSE
                        coeff87 WHEN ( cur_count = to_unsigned(86, 7) ) ELSE
                        coeff88 WHEN ( cur_count = to_unsigned(87, 7) ) ELSE
                        coeff89 WHEN ( cur_count = to_unsigned(88, 7) ) ELSE
                        coeff90 WHEN ( cur_count = to_unsigned(89, 7) ) ELSE
                        coeff91 WHEN ( cur_count = to_unsigned(90, 7) ) ELSE
                        coeff92 WHEN ( cur_count = to_unsigned(91, 7) ) ELSE
                        coeff93 WHEN ( cur_count = to_unsigned(92, 7) ) ELSE
                        coeff94 WHEN ( cur_count = to_unsigned(93, 7) ) ELSE
                        coeff95 WHEN ( cur_count = to_unsigned(94, 7) ) ELSE
                        coeff96 WHEN ( cur_count = to_unsigned(95, 7) ) ELSE
                        coeff97 WHEN ( cur_count = to_unsigned(96, 7) ) ELSE
                        coeff98 WHEN ( cur_count = to_unsigned(97, 7) ) ELSE
                        coeff99 WHEN ( cur_count = to_unsigned(98, 7) ) ELSE
                        coeff100 WHEN ( cur_count = to_unsigned(99, 7) ) ELSE
                        coeff101 WHEN ( cur_count = to_unsigned(100, 7) ) ELSE
                        coeff102 WHEN ( cur_count = to_unsigned(101, 7) ) ELSE
                        coeff103 WHEN ( cur_count = to_unsigned(102, 7) ) ELSE
                        coeff104 WHEN ( cur_count = to_unsigned(103, 7) ) ELSE
                        coeff105 WHEN ( cur_count = to_unsigned(104, 7) ) ELSE
                        coeff106 WHEN ( cur_count = to_unsigned(105, 7) ) ELSE
                        coeff107 WHEN ( cur_count = to_unsigned(106, 7) ) ELSE
                        coeff108 WHEN ( cur_count = to_unsigned(107, 7) ) ELSE
                        coeff109 WHEN ( cur_count = to_unsigned(108, 7) ) ELSE
                        coeff110 WHEN ( cur_count = to_unsigned(109, 7) ) ELSE
                        coeff111 WHEN ( cur_count = to_unsigned(110, 7) ) ELSE
                        coeff112 WHEN ( cur_count = to_unsigned(111, 7) ) ELSE
                        coeff113 WHEN ( cur_count = to_unsigned(112, 7) ) ELSE
                        coeff114 WHEN ( cur_count = to_unsigned(113, 7) ) ELSE
                        coeff115 WHEN ( cur_count = to_unsigned(114, 7) ) ELSE
                        coeff116 WHEN ( cur_count = to_unsigned(115, 7) ) ELSE
                        coeff117 WHEN ( cur_count = to_unsigned(116, 7) ) ELSE
                        coeff118 WHEN ( cur_count = to_unsigned(117, 7) ) ELSE
                        coeff119 WHEN ( cur_count = to_unsigned(118, 7) ) ELSE
                        coeff120 WHEN ( cur_count = to_unsigned(119, 7) ) ELSE
                        coeff121 WHEN ( cur_count = to_unsigned(120, 7) ) ELSE
                        coeff122 WHEN ( cur_count = to_unsigned(121, 7) ) ELSE
                        coeff123 WHEN ( cur_count = to_unsigned(122, 7) ) ELSE
                        coeff124 WHEN ( cur_count = to_unsigned(123, 7) ) ELSE
                        coeff125 WHEN ( cur_count = to_unsigned(124, 7) ) ELSE
                        coeff126 WHEN ( cur_count = to_unsigned(125, 7) ) ELSE
                        coeff127 WHEN ( cur_count = to_unsigned(126, 7) ) ELSE
                        coeff128;
  mul_temp <= inputmux_1 * product_1_mux;
  product_1 <= resize(shift_right(mul_temp(36) & mul_temp(36 DOWNTO 0) + ( "0" & (mul_temp(2) & NOT mul_temp(2))), 2), 36);

  prod_typeconvert_1 <= resize(product_1, 39);

  add_temp <= resize(prod_typeconvert_1, 40) + resize(acc_out_1, 40);
  acc_sum_1 <= add_temp(38 DOWNTO 0);

  acc_in_1 <= prod_typeconvert_1 WHEN ( phase_0 = '1' ) ELSE
                   acc_sum_1;

  Acc_reg_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_out_1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        acc_out_1 <= acc_in_1;
      END IF;
    END IF;
  END PROCESS Acc_reg_1_process;

  Finalsum_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_final <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        acc_final <= acc_out_1;
      END IF;
    END IF;
  END PROCESS Finalsum_reg_process;

  output_typeconvert <= resize(shift_right(acc_final(35 DOWNTO 0) + ( "0" & (acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26) & NOT acc_final(26))), 26), 10);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_127 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF;
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
